package pack01_exceptionhandling.sec03_ThrowsException.EX02_ThrowsException_2;

/*최상위 메서드인 main() 메서드가 예외를 전가한 경우*/

public class EX02_ThrowsException_2 {
	public static void main(String[] args) throws Exception{
		Class cls = Class.forName("java.lang.Object2");
	}
}
